// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXrPJ9jVazV0-7xSITmzxkTDXPVVKrg7c',
    appId: '1:813053928991:web:1f4d0888fa0160833e572a',
    messagingSenderId: '813053928991',
    projectId: 'bulletnote-16b7d',
    authDomain: 'bulletnote-16b7d.firebaseapp.com',
    storageBucket: 'bulletnote-16b7d.appspot.com',
    measurementId: 'G-K1525SSB5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg6pMNpeej5QdYRc5yF6Akq8R3uH0anXQ',
    appId: '1:813053928991:android:6a121cc5cc42855b3e572a',
    messagingSenderId: '813053928991',
    projectId: 'bulletnote-16b7d',
    storageBucket: 'bulletnote-16b7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1BqtZ0ftWK5mDTmBqodT2r7uhsUv6pcU',
    appId: '1:813053928991:ios:449cf11d2e12ba163e572a',
    messagingSenderId: '813053928991',
    projectId: 'bulletnote-16b7d',
    storageBucket: 'bulletnote-16b7d.appspot.com',
    iosClientId: '813053928991-ccko7vgj2nt78s3vmr3riq8d5juv7f4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1BqtZ0ftWK5mDTmBqodT2r7uhsUv6pcU',
    appId: '1:813053928991:ios:449cf11d2e12ba163e572a',
    messagingSenderId: '813053928991',
    projectId: 'bulletnote-16b7d',
    storageBucket: 'bulletnote-16b7d.appspot.com',
    iosClientId: '813053928991-ccko7vgj2nt78s3vmr3riq8d5juv7f4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingFlutter',
  );
}
